version: '31.7'
services:
  t6proj-postgres:
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: qwe

volumes:
  pgdata: