server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
adminlte:
  page-title: Отдел кадров
  project-name: Отдел кадров
  navigation:
    title: Навигация